<?php

use App\Models\Member;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('full mobile auth flow strictly follows state machine', function () {
    // 1. Registration
    $regResponse = $this->postJson(route('api.v1.auth.register'), [
        'name' => 'State Machine User',
        'email' => 'state@example.com',
        'phone' => '12345678',
        'password' => 'password123',
        'password_confirmation' => 'password123',
        'date_of_birth' => '1990-01-01',
        'gender' => 'male',
    ]);

    $regResponse->assertStatus(201);
    $regResponse->assertJsonPath('data.state', 'pending_verification');

    $member = Member::where('email', 'state@example.com')->first();
    expect($member->status)->toBe('pending_verification');

    // 2. Login while unverified
    $loginResponse = $this->postJson(route('api.v1.auth.login'), [
        'email' => 'state@example.com',
        'password' => 'password123',
    ]);

    $loginResponse->assertStatus(200);
    $loginResponse->assertJsonPath('data.code', 'ADDITIONAL_VERIFICATION_REQUIRED');
    $loginResponse->assertJsonPath('data.state', 'pending_additional_verification');

    // 3. OTP Verification
    // Since we're in a test, we can manually set the OTP in the DB
    // In a real flow, OTP is generated by register() or send-otp()
    $otp = '123456';
    $member->update([
        'otp_code' => $otp,
        'otp_expires_at' => now()->addMinutes(10),
    ]);

    $verifyResponse = $this->postJson(route('api.v1.auth.verify-otp'), [
        'identifier' => 'state@example.com',
        'otp' => $otp,
    ]);

    $verifyResponse->assertStatus(200);
    $verifyResponse->assertJsonPath('data.state', 'pending_onboarding');
    $verifyResponse->assertJsonStructure(['data' => ['token']]);

    $token = $verifyResponse->json('data.token');
    $member->refresh();
    expect($member->status)->toBe('pending_onboarding');

    // 4. Phone Verification
    $otp = '654321';
    $member->update([
        'otp_code' => $otp,
        'otp_expires_at' => now()->addMinutes(10),
    ]);

    $verifyPhoneResponse = $this->withToken($token)->postJson(route('api.v1.auth.verify-phone'), [
        'phone' => '12345678',
        'otp' => $otp,
    ]);

    $verifyPhoneResponse->assertStatus(200);
    $verifyPhoneResponse->assertJsonPath('data.state', 'pending_onboarding');
    $verifyPhoneResponse->assertJsonStructure(['data' => ['token']]);

    $token = $verifyPhoneResponse->json('data.token');
    $member->refresh();
    expect($member->status)->toBe('pending_onboarding');

    // 5. Access protected route with limited token
    $profileResponse = $this->withToken($token)->getJson(route('api.v1.member.profile'));
    $profileResponse->assertStatus(403);
    $profileResponse->assertJsonPath('state', 'pending_onboarding');

    // 6. Complete Registration (Final Onboarding)
    $completeResponse = $this->withToken($token)->postJson(route('api.v1.auth.complete-registration'), [
        'name' => 'State Machine User',
        'email' => 'state@example.com',
        'phone' => '12345678',
        'date_of_birth' => '1990-01-01',
        'gender' => 'male',
        'is_parent_account' => true,
    ]);

    $completeResponse->assertStatus(201);
    $completeResponse->assertJsonPath('data.state', 'active');
    $completeResponse->assertJsonStructure(['data' => ['token', 'user']]);

    $member->refresh();
    expect($member->status)->toBe('active');
    expect($member->isOnboardingCompleted())->toBeTrue();

    // 7. Access protected route with full token
    $newToken = $completeResponse->json('data.token');
    $profileResponse = $this->withToken($newToken)->getJson(route('api.v1.member.profile'));
    $profileResponse->assertStatus(200);
});
